### ISSUE TITLE
Support for configuring IMessagePropertyProvider instances?

### ISSUE THREAD

**Issue by drub0y** [christopherread/Obvs#8] opened 2015-04-03 01:06 UTC
I don't see any support for configuring `IMessagePropertyProvider<TMessage>` instances during configuration. All existing implementations appear to be just doing `new DefaultPropertyProvider<TMessage>()` in a hardcoded fashion (which I've also copied the behavior of for now).

Should this be something provided by the base fluent configuration APIs? Or perhaps I am misunderstanding the goal of property providers? Was it ever the intention that higher level consumers of the API could inject additional property providers? 

The scenario I was thinking of is that, in Azure Service Bus Subscriptions, you can filter on properties for a subscription, but not on the details serialized in the body. Therefore if you wanted to broadcast events to a topic that subscribers could theoretically filter out based on properties, you would need to be able to supply your own `IMessagePropertyProvider<TMessage>` implementation that knew exactly how to extract those properties for a given `TMessage`. 

For example, if I have an `IEvent` called `OrderSubmitted` that maybe has a `PartnerId` property on it and I'm broadcasting those events to a topic, but want to make sure that subscribers can filter on that `PartnerId` I would expect to write a custom `OrderSubmittedEventPropertyProvider` that provides explicit support for pulling that out into a property and then I'd need a way to configure that. Of course you could imagine more advanced, generic implementations based on C# expressions, but this is just a very simple example.

The other thing this raises is that, if you _can_ configure property providers, then likely the API should allow for configuring multiple providers. One way to do that would be some kind of `CompositePropertyProvider<TMessage>` that allows for adding more than one for a `TMessage` and executes them all so that `IMessagePublisher<TMessage>` implementations can always work with just `IMessagePropertyProvider<TMessage>` so that they are agnostic of one or many.

**Comment by inter8ection** [comment] 2015-04-04 13:12
Hi, yes it works the same way with ActiveMQ subscriptions. It was originally intended to be used for the Request/Response correlation Id's, but the issue is that as messages are only exposed as an IObservable there is no easy way to specify a predicate that gets passed down to the transport implementation, except at construction time. So instead I am just filtering Request/Response within Obvs itself - the trade off being every ServiceBus will receive every Response for all Endpoints it is configured to listen to.

For publishing there is the possibility to add configuration methods for a MessagePropertyProvider that knows how to pull properties off a given message type, but without the corresponding subscription option it doesn't seem very useful.

**Comment by drub0y** [comment] 2015-04-06 22:21
> Hi, yes it works the same way with ActiveMQ subscriptions. It was originally intended to be used for the Request/Response correlation Id's, but the issue is that as messages are only exposed as an IObservable there is no easy way to specify a predicate that gets passed down to the transport implementation, except at construction time. So instead I am just filtering Request/Response within Obvs itself - the trade off being every ServiceBus will receive every Response for all Endpoints it is configured to listen to.

Yes, you'd have to make the switch to [`IQbservable`](https://msdn.microsoft.com/en-us/library/hh229328(v=vs.103).aspx) if you wanted the ability to filter as part of some dynamic subscription. That would be totally awesome, but it's a bigger step fwd. Definitely something to consider down the road though!

> For publishing there is the possibility to add configuration methods for a MessagePropertyProvider that knows how to pull properties off a given message type, but without the corresponding subscription option it doesn't seem very useful.

Yes, this is definitely more what I had in mind in the near term. I at least want to have the ability to configure things so the data gets put there even if I can't do dynamic subscriptions that take advantage of it right now. At least if the properties are published, I can have static subscriptions that take advantage of filters or setup dynamic ones outside of the Obvs APIs right now.

**Comment by megakid** [comment] 2019-01-01 22:33
Closing

**Closed by megakid** 2019-01-01 22:33 UTC
Labels: suggestion
